export type Device='desktop'|'tablet'|'mobile';
export type ContentKey='eyebrow'|'title'|'description'|'date'|'location'|'stores'|'primaryButton'|'secondaryButton';
export type Layer='background'|'header'|'logo'|'content'|'simulator'|'footer';
export type Action='simulator'|'vehicles'|'whatsapp'|'none';
export type Align='left'|'center'|'right';
export type Box={x:number;y:number;width:number;visible:boolean;locked:boolean};
export type Visual={text:string;fontSize:number;color:string;background:string;borderColor:string;opacity:number;weight:number;align:Align;lineHeight:number;letterSpacing:number;radius:number;paddingX:number;paddingY:number;action:Action};
export type DeviceLayout={heroHeight:number;backgroundScale:number;backgroundX:number;backgroundY:number;header:Box;logo:Box;simulator:Box;content:Record<ContentKey,Box>};
export type Footer={visible:boolean;backgroundColor:string;textColor:string;align:Align;fontSize:number;maxWidth:number;paddingY:number;showTerms:boolean;notice:string;termsOverride:string};
export type Draft={primaryColor:string;secondaryColor:string;overlay:number;headerLogo:string;headerLabel:string;showHeaderLabel:boolean;eventLogo:string;backgroundMode:Record<Device,'original'|'custom'|'none'>;backgroundData:Record<Device,string>;content:Record<ContentKey,Visual>;footer:Footer;devices:Record<Device,DeviceLayout>;cardRadius:number;updatedAt:string};
export type Drag={pointerId:number;kind:'box'|'resize'|'content'|'contentResize'|'background';key?:'header'|'logo'|'simulator';contentKey?:ContentKey;startX:number;startY:number;origin:Box|{x:number;y:number};device:Device};

export const devices:Device[]=['desktop','tablet','mobile'];
export const widths:Record<Device,number>={desktop:1440,tablet:768,mobile:390};
export const deviceNames:Record<Device,string>={desktop:'Desktop',tablet:'Tablet',mobile:'Mobile'};
export const contentKeys:ContentKey[]=['eyebrow','title','description','date','location','stores','primaryButton','secondaryButton'];
export const contentNames:Record<ContentKey,string>={eyebrow:'Chamada superior',title:'Título',description:'Descrição',date:'Data do evento',location:'Local do evento',stores:'Quantidade de lojas',primaryButton:'Botão principal',secondaryButton:'Botão secundário'};
export const defaultHeader='/campaign-assets/auto-sede-logo-cropped.png';
export const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
export const bx=(x:number,y:number,width:number,visible=true):Box=>({x,y,width,visible,locked:false});

function contentBoxes(device:Device):Record<ContentKey,Box>{
 if(device==='mobile')return{eyebrow:bx(6,18,72),title:bx(6,23,88),description:bx(6,37,88),date:bx(6,46,42),location:bx(51,46,43),stores:bx(6,51,55),primaryButton:bx(6,57,45),secondaryButton:bx(54,57,40)};
 if(device==='tablet')return{eyebrow:bx(6,18,44),title:bx(6,23,86),description:bx(6,36,78),date:bx(6,44,28),location:bx(36,44,30),stores:bx(68,44,26),primaryButton:bx(6,50,30),secondaryButton:bx(38,50,25)};
 return{eyebrow:bx(4,19,24),title:bx(4,24,37),description:bx(4,41,36),date:bx(4,53,13),location:bx(18,53,15),stores:bx(34,53,14),primaryButton:bx(4,60,15),secondaryButton:bx(20,60,13)};
}
function layout(device:Device):DeviceLayout{
 if(device==='mobile')return{heroHeight:2050,backgroundScale:100,backgroundX:50,backgroundY:50,header:bx(5,2.5,48),logo:bx(6,9,50),simulator:bx(5,66,90),content:contentBoxes(device)};
 if(device==='tablet')return{heroHeight:1680,backgroundScale:100,backgroundX:50,backgroundY:50,header:bx(3,2.5,28),logo:bx(5,9,34),simulator:bx(6,60,88),content:contentBoxes(device)};
 return{heroHeight:1180,backgroundScale:100,backgroundX:50,backgroundY:50,header:bx(2,2.5,16),logo:bx(4,9,22),simulator:bx(43,10,55),content:contentBoxes(device)};
}
function visual(text:string,fontSize:number,extra:Partial<Visual>={}):Visual{return{text,fontSize,color:'#FFFFFF',background:'#00000000',borderColor:'#FFFFFF33',opacity:100,weight:800,align:'left',lineHeight:1.1,letterSpacing:0,radius:16,paddingX:0,paddingY:0,action:'none',...extra};}
export function defaults(c:any):Draft{return{primaryColor:c?.primary_color||'#DC2626',secondaryColor:c?.secondary_color||'#071020',overlay:76,headerLogo:'',headerLabel:'APOIO',showHeaderLabel:true,eventLogo:'',backgroundMode:{desktop:'original',tablet:'original',mobile:'original'},backgroundData:{desktop:'',tablet:'',mobile:''},content:{eyebrow:visual(c?.hero_eyebrow||'Financiamento de veículos',12,{background:'#00000040',radius:999,paddingX:16,paddingY:9,letterSpacing:2,weight:900}),title:visual(c?.title||'Escolha seu carro e faça uma simulação do seu financiamento',64,{weight:900,lineHeight:.98,letterSpacing:-2}),description:visual(c?.description||'Escolha um veículo, preencha seus dados e receba uma simulação.',18,{color:'#FFFFFFD9',weight:500,lineHeight:1.45}),date:visual('',12,{background:'#00000040',radius:999,paddingX:13,paddingY:9,weight:900}),location:visual('',12,{background:'#00000040',radius:999,paddingX:13,paddingY:9,weight:900}),stores:visual('',12,{background:'#00000040',radius:999,paddingX:13,paddingY:9,weight:900}),primaryButton:visual(c?.cta_label||'Simular agora',14,{background:c?.primary_color||'#DC2626',borderColor:'#00000000',radius:999,paddingX:28,paddingY:15,weight:900,align:'center',action:'simulator'}),secondaryButton:visual('Ver veículos',14,{background:'#FFFFFF1A',borderColor:'#FFFFFF40',radius:999,paddingX:28,paddingY:15,weight:900,align:'center',action:'vehicles'})},footer:{visible:true,backgroundColor:c?.secondary_color||'#071020',textColor:'#CBD5E1',align:'center',fontSize:12,maxWidth:1150,paddingY:32,showTerms:true,notice:'© {ANO} Auto Sede. Condições sujeitas à análise e confirmação da loja responsável.',termsOverride:''},devices:{desktop:layout('desktop'),tablet:layout('tablet'),mobile:layout('mobile')},cardRadius:30,updatedAt:new Date().toISOString()};}
function safeBox(v:any,f:Box,min=5):Box{const width=clamp(Number(v?.width??f.width),min,100);return{x:clamp(Number(v?.x??f.x),0,100-width),y:clamp(Number(v?.y??f.y),0,98),width,visible:v?.visible!==false,locked:v?.locked===true};}
export function safe(raw:any,c:any):Draft{const f=defaults(c);if(!raw||typeof raw!=='object')return f;const next={...f,...raw};next.content={...f.content};for(const k of contentKeys)next.content[k]={...f.content[k],...(raw.content?.[k]||{})};next.footer={...f.footer,...(raw.footer||{})};next.devices={...f.devices};for(const d of devices){const src=raw.devices?.[d]||raw.layouts?.[d]||{};const base=f.devices[d];const cb={} as Record<ContentKey,Box>;for(const k of contentKeys)cb[k]=safeBox(src.content?.[k]||src.contentBoxes?.[k],base.content[k],k==='title'||k==='description'?12:6);next.devices[d]={...base,...src,heroHeight:clamp(Number(src.heroHeight??src.heroMinHeight??base.heroHeight),600,3000),backgroundScale:clamp(Number(src.backgroundScale??src.backgroundZoom??base.backgroundScale),1,1000),backgroundX:clamp(Number(src.backgroundX??base.backgroundX),-200,300),backgroundY:clamp(Number(src.backgroundY??base.backgroundY),-200,300),header:safeBox(src.header||src.boxes?.headerSupport,base.header),logo:safeBox(src.logo||src.boxes?.logo,base.logo),simulator:safeBox(src.simulator||src.boxes?.simulator,base.simulator,44),content:cb};}return next;}
export function storageKey(c:any){return`auto-sede:landing-visual:draft:${c?.id||c?.slug||'new'}`;}
function date(v?:string){if(!v)return'';const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('pt-BR');}
export function textFor(k:ContentKey,d:Draft,c:any,e:any,stores:any[]){if(d.content[k].text)return d.content[k].text;if(k==='eyebrow')return c?.hero_eyebrow||'Financiamento de veículos';if(k==='title')return c?.title||'Escolha seu carro e faça uma simulação do seu financiamento';if(k==='description')return c?.description||'Escolha um veículo, preencha seus dados e receba uma simulação.';if(k==='date'){const a=date(e?.start_date),b=date(e?.end_date);return a&&b?`${a} a ${b}`:a||b||'Data a confirmar';}if(k==='location')return[e?.location,e?.city,e?.state].filter(Boolean).join(' • ')||'Local a confirmar';if(k==='stores')return`${stores.length||c?.store_count||0} loja(s) participante(s)`;if(k==='primaryButton')return c?.cta_label||'Simular agora';return'Ver veículos';}
export async function optimize(file:File,logo=false){if(!file.type.startsWith('image/'))throw new Error('Selecione uma imagem válida.');if(file.size>20*1024*1024)throw new Error('Imagem acima de 20 MB.');const url=URL.createObjectURL(file);try{const img=await new Promise<HTMLImageElement>((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=()=>no(new Error('Não foi possível ler a imagem.'));i.src=url;});const maxW=logo?1400:2400,maxH=logo?1000:1800,s=Math.min(maxW/img.naturalWidth,maxH/img.naturalHeight,1);const cv=document.createElement('canvas');cv.width=Math.max(1,Math.round(img.naturalWidth*s));cv.height=Math.max(1,Math.round(img.naturalHeight*s));const ctx=cv.getContext('2d');if(!ctx)throw new Error('Falha ao processar imagem.');ctx.drawImage(img,0,0,cv.width,cv.height);return cv.toDataURL(logo&&file.type==='image/png'?'image/png':'image/jpeg',.84);}finally{URL.revokeObjectURL(url);}}
