'use client';

import { Settings2 } from 'lucide-react';
import { AssetPanel, BoxPanel, Color, Field, Num, Select, Switch } from './CampaignVisualEditorControls';
import type { Action, Align, ContentKey } from './CampaignVisualEditorModel';
import { contentKeys, contentNames, defaultHeader, textFor } from './CampaignVisualEditorModel';

export function CampaignVisualEditorInspector(p:any){
 const {layer,draft,device,layout,campaign,eventInfo,stores,selectedContent}=p;
 const title=layer==='background'?'Imagem de fundo':layer==='header'?'Cabeçalho / Apoio':layer==='logo'?'Logomarca':layer==='simulator'?'Simulador':layer==='footer'?'Rodapé oficial':contentNames[selectedContent as ContentKey];
 const visual=draft.content[selectedContent];
 return <aside className="overflow-y-auto bg-white p-4"><div className="flex items-center gap-2"><Settings2 size={17}/><strong>{title}</strong></div>
 {layer==='background'?<><AssetPanel source={p.heroSource} inputRef={p.bgInput} id={`bg-${device}`} onFile={(f:any)=>p.asset(f,'background')} onRemove={()=>p.setBackgroundMode('none')} onRestore={()=>p.setBackgroundMode('original')}/><div className="mt-3 rounded-xl bg-indigo-50 p-3 text-xs font-bold text-indigo-700">Clique na imagem e arraste. Use a roda do mouse para escala livre.</div><Switch label="Edição ativa" value={p.bgEdit} onChange={p.setBgEdit}/><Num label="Escala" value={layout.backgroundScale} min={1} max={1000} suffix="%" onChange={(backgroundScale:number)=>p.patchLayout({backgroundScale})}/><Num label="Posição horizontal" value={layout.backgroundX} min={-200} max={300} suffix="%" onChange={(backgroundX:number)=>p.patchLayout({backgroundX})}/><Num label="Posição vertical" value={layout.backgroundY} min={-200} max={300} suffix="%" onChange={(backgroundY:number)=>p.patchLayout({backgroundY})}/></>:null}
 {layer==='header'?<><AssetPanel source={draft.headerLogo||defaultHeader} inputRef={p.headerInput} id="header-file" onFile={(f:any)=>p.asset(f,'header')} onRemove={()=>p.commit({...draft,headerLogo:''})}/><Field label="Texto de apoio" value={draft.headerLabel} onChange={(headerLabel:string)=>p.commit({...draft,headerLabel})}/><Switch label="Exibir texto" value={draft.showHeaderLabel} onChange={(showHeaderLabel:boolean)=>p.commit({...draft,showHeaderLabel})}/><BoxPanel box={layout.header} min={7} onChange={(x:any)=>p.patchBox('header',x)}/></>:null}
 {layer==='logo'?<><AssetPanel source={draft.eventLogo||campaign?.logo_url||''} inputRef={p.logoInput} id="logo-file" onFile={(f:any)=>p.asset(f,'logo')} onRemove={()=>p.commit({...draft,eventLogo:''})}/><BoxPanel box={layout.logo} min={7} onChange={(x:any)=>p.patchBox('logo',x)}/></>:null}
 {layer==='content'?<><div className="mt-4 grid grid-cols-2 gap-2">{contentKeys.map(k=><button key={k} onClick={()=>p.selectText(k)} className={`rounded-xl p-2 text-[10px] font-black ${selectedContent===k?'bg-fuchsia-600 text-white':'bg-zinc-100'}`}>{contentNames[k]}</button>)}</div><label className="mt-4 block text-xs font-black">Texto<textarea id={`text-${selectedContent}`} value={visual.text} placeholder={textFor(selectedContent,{...draft,content:{...draft.content,[selectedContent]:{...visual,text:''}}},campaign,eventInfo,stores)} onChange={e=>p.patchVisual(selectedContent,{text:e.target.value})} className="mt-2 min-h-24 w-full rounded-xl border p-3"/></label><BoxPanel box={layout.content[selectedContent]} min={selectedContent==='title'||selectedContent==='description'?12:6} onChange={(x:any)=>p.patchContentBox(selectedContent,x)}/><Num label="Tamanho da fonte" value={visual.fontSize} min={8} max={160} suffix="px" onChange={(fontSize:number)=>p.patchVisual(selectedContent,{fontSize})}/><Select label="Peso" value={String(visual.weight)} options={['100','200','300','400','500','600','700','800','900']} onChange={v=>p.patchVisual(selectedContent,{weight:Number(v)})}/><Select label="Alinhamento" value={visual.align} options={['left','center','right']} onChange={v=>p.patchVisual(selectedContent,{align:v as Align})}/><Color label="Cor do texto" value={visual.color} onChange={color=>p.patchVisual(selectedContent,{color})}/><Color label="Fundo" value={visual.background} alpha onChange={background=>p.patchVisual(selectedContent,{background})}/><Color label="Borda" value={visual.borderColor} alpha onChange={borderColor=>p.patchVisual(selectedContent,{borderColor})}/><Num label="Opacidade" value={visual.opacity} min={0} max={100} suffix="%" onChange={(opacity:number)=>p.patchVisual(selectedContent,{opacity})}/><Num label="Altura da linha" value={visual.lineHeight} min={.7} max={3} suffix="x" onChange={(lineHeight:number)=>p.patchVisual(selectedContent,{lineHeight})}/><Num label="Letras" value={visual.letterSpacing} min={-8} max={30} suffix="px" onChange={(letterSpacing:number)=>p.patchVisual(selectedContent,{letterSpacing})}/><Num label="Curvatura" value={visual.radius} min={0} max={999} suffix="px" onChange={(radius:number)=>p.patchVisual(selectedContent,{radius})}/><Num label="Padding horizontal" value={visual.paddingX} min={0} max={80} suffix="px" onChange={(paddingX:number)=>p.patchVisual(selectedContent,{paddingX})}/><Num label="Padding vertical" value={visual.paddingY} min={0} max={60} suffix="px" onChange={(paddingY:number)=>p.patchVisual(selectedContent,{paddingY})}/>{selectedContent.includes('Button')?<Select label="Ação" value={visual.action} options={['simulator','vehicles','whatsapp','none']} onChange={v=>p.patchVisual(selectedContent,{action:v as Action})}/>:null}</>:null}
 {layer==='simulator'?<><div className="mt-4 rounded-xl bg-emerald-50 p-3 text-xs font-bold text-emerald-800">Use a alça superior para mover sem bloquear os campos.</div><BoxPanel box={layout.simulator} min={44} onChange={(x:any)=>p.patchBox('simulator',x)}/><Num label="Curvatura" value={draft.cardRadius} min={0} max={80} suffix="px" onChange={(cardRadius:number)=>p.commit({...draft,cardRadius})}/></>:null}
 {layer==='footer'?<><Switch label="Exibir rodapé" value={draft.footer.visible} onChange={(visible:boolean)=>p.commit({...draft,footer:{...draft.footer,visible}})}/><Field label="Aviso principal" value={draft.footer.notice} textarea onChange={(notice:string)=>p.commit({...draft,footer:{...draft.footer,notice}})}/><Switch label="Exibir termos" value={draft.footer.showTerms} onChange={(showTerms:boolean)=>p.commit({...draft,footer:{...draft.footer,showTerms}})}/><Field label="Termos personalizados" value={draft.footer.termsOverride} textarea placeholder={campaign?.terms_text||'Sem termos cadastrados.'} onChange={(termsOverride:string)=>p.commit({...draft,footer:{...draft.footer,termsOverride}})}/><Color label="Fundo do rodapé" value={draft.footer.backgroundColor} onChange={backgroundColor=>p.commit({...draft,footer:{...draft.footer,backgroundColor}})}/><Color label="Texto do rodapé" value={draft.footer.textColor} onChange={textColor=>p.commit({...draft,footer:{...draft.footer,textColor}})}/><Select label="Alinhamento" value={draft.footer.align} options={['left','center','right']} onChange={v=>p.commit({...draft,footer:{...draft.footer,align:v as Align}})}/><Num label="Fonte" value={draft.footer.fontSize} min={9} max={32} suffix="px" onChange={(fontSize:number)=>p.commit({...draft,footer:{...draft.footer,fontSize}})}/><Num label="Largura máxima" value={draft.footer.maxWidth} min={320} max={1800} suffix="px" onChange={(maxWidth:number)=>p.commit({...draft,footer:{...draft.footer,maxWidth}})}/><Num label="Espaçamento vertical" value={draft.footer.paddingY} min={12} max={120} suffix="px" onChange={(paddingY:number)=>p.commit({...draft,footer:{...draft.footer,paddingY}})}/></>:null}
 <div className="mt-6 border-t pt-5"><strong className="text-sm">Aparência geral</strong><Color label="Cor principal" value={draft.primaryColor} onChange={primaryColor=>p.commit({...draft,primaryColor})}/><Color label="Cor do banner" value={draft.secondaryColor} onChange={secondaryColor=>p.commit({...draft,secondaryColor})}/><Num label="Escurecimento" value={draft.overlay} min={0} max={95} suffix="%" onChange={(overlay:number)=>p.commit({...draft,overlay})}/><Num label="Altura do banner" value={layout.heroHeight} min={600} max={3000} suffix="px" onChange={(heroHeight:number)=>p.patchLayout({heroHeight})}/></div></aside>;
}
