'use client';

import { Eye, EyeOff, ImagePlus, Lock, RotateCcw, Trash2, Unlock, Upload } from 'lucide-react';
import type { Box } from './CampaignVisualEditorModel';
import { clamp } from './CampaignVisualEditorModel';

export function Num({label,value,min,max,suffix='',onChange}:{label:string;value:number;min:number;max:number;suffix?:string;onChange:(n:number)=>void}){return <label className="mt-4 block"><span className="flex justify-between text-xs font-black"><span>{label}</span><span>{Math.round(value*10)/10}{suffix}</span></span><input type="range" min={min} max={max} step="0.5" value={clamp(value,min,max)} onChange={e=>onChange(Number(e.target.value))} className="mt-2 w-full"/><input type="number" min={min} max={max} step="0.5" value={Math.round(value*10)/10} onChange={e=>onChange(clamp(Number(e.target.value),min,max))} className="mt-1 h-9 w-full rounded-lg bg-zinc-50 px-3 text-xs font-black"/></label>;}
export function Color({label,value,onChange,alpha=false}:{label:string;value:string;onChange:(v:string)=>void;alpha?:boolean}){const v=/^#[0-9a-fA-F]{6}/.test(value)?value.slice(0,7):'#000000';return <label className="mt-4 block text-xs font-black">{label}<div className="mt-2 flex gap-2"><input type="color" value={v} onChange={e=>onChange(e.target.value.toUpperCase()+(alpha?'FF':''))}/><input value={value} onChange={e=>onChange(e.target.value.toUpperCase())} className="h-10 flex-1 rounded-lg bg-zinc-50 px-3 font-mono text-xs"/></div></label>;}
export function Field({label,value,onChange,textarea=false,placeholder}:{label:string;value:string;onChange:(v:string)=>void;textarea?:boolean;placeholder?:string}){return <label className="mt-4 block text-xs font-black">{label}{textarea?<textarea value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border p-3"/>:<input value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} className="mt-2 h-11 w-full rounded-xl border px-3"/>}</label>;}
export function Switch({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="mt-4 flex items-center justify-between rounded-xl bg-zinc-50 p-3 text-xs font-black">{label}<input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/></label>;}
export function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label className="mt-4 block text-xs font-black">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-2 h-11 w-full rounded-xl border px-3">{options.map(o=><option key={o} value={o}>{o}</option>)}</select></label>;}
export function BoxPanel({box,min,onChange}:{box:Box;min:number;onChange:(p:Partial<Box>)=>void}){return <div className="mt-4"><Switch label="Exibir" value={box.visible} onChange={visible=>onChange({visible})}/><Switch label="Bloquear" value={box.locked} onChange={locked=>onChange({locked})}/><Num label="Horizontal" value={box.x} min={0} max={Math.max(0,100-box.width)} suffix="%" onChange={x=>onChange({x})}/><Num label="Vertical" value={box.y} min={0} max={98} suffix="%" onChange={y=>onChange({y})}/><Num label="Largura" value={box.width} min={min} max={100-box.x} suffix="%" onChange={width=>onChange({width})}/></div>;}
export function AssetPanel({source,inputRef,id,onFile,onRemove,onRestore}:{source:string;inputRef:React.MutableRefObject<HTMLInputElement|null>;id:string;onFile:(f:File|undefined)=>void;onRemove:()=>void;onRestore?:()=>void}){return <div className="mt-4 rounded-2xl border p-3"><label htmlFor={id} className="flex min-h-32 cursor-pointer items-center justify-center rounded-xl bg-zinc-100 p-3">{source?<img src={source} alt="Prévia" className="max-h-28 max-w-full object-contain"/>:<ImagePlus size={34}/>}</label><input ref={inputRef} id={id} type="file" accept="image/*" className="sr-only" onChange={e=>{onFile(e.currentTarget.files?.[0]);e.currentTarget.value='';}}/><div className="mt-3 grid grid-cols-2 gap-2"><label htmlFor={id} className="cursor-pointer rounded-xl bg-indigo-600 p-3 text-center text-xs font-black text-white"><Upload size={14} className="inline"/> Trocar</label><button onClick={onRemove} className="rounded-xl bg-red-50 text-xs font-black text-red-700"><Trash2 size={14} className="inline"/> Remover</button>{onRestore?<button onClick={onRestore} className="col-span-2 rounded-xl border p-3 text-xs font-black"><RotateCcw size={14} className="inline"/> Restaurar original</button>:null}</div></div>;}
export function LayerRow({label,active,box,onSelect,onVisible,onLock}:{label:string;active:boolean;box?:Box;onSelect:()=>void;onVisible?:()=>void;onLock?:()=>void}){return <div className={`flex min-h-11 items-center gap-1 rounded-xl border px-2 ${active?'border-indigo-300 bg-indigo-50':'border-zinc-200'}`}><button type="button" onClick={onSelect} className="flex-1 text-left text-[11px] font-black">{label}</button>{onVisible?<button type="button" onClick={onVisible} className="h-8 w-8">{box?.visible?<Eye size={14}/>:<EyeOff size={14}/>}</button>:null}{onLock?<button type="button" onClick={onLock} className="h-8 w-8">{box?.locked?<Lock size={14}/>:<Unlock size={14}/>}</button>:null}</div>;}
