'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Archive, BookOpen, CheckCircle2, FileText, LibraryBig, Loader2, LockKeyhole, RefreshCw, Store, Upload, XCircle } from 'lucide-react';
import { createClient } from '@/lib/supabase';

type KnowledgeDocument = { id:string; scope:'method'|'store'; store_id:string|null; title:string; original_filename:string; mime_type:string; file_size_bytes:number; status:'uploaded'|'processing'|'ready'|'failed'|'archived'; extracted_characters:number; chunk_count:number; embedding_model:string|null; extraction_error:string|null; created_at:string };
type PreparedUpload = { storage_path:string; signed_url:string; mime_type:string; max_file_bytes:number; expires_in_seconds:number };
const MAX_FILE_BYTES=25*1024*1024;
function formatBytes(v:number){if(v<1024)return `${v} B`;if(v<1048576)return `${(v/1024).toFixed(1)} KB`;return `${(v/1048576).toFixed(1)} MB`}
function statusLabel(s:KnowledgeDocument['status']){if(s==='ready')return'Pronto para consulta';if(s==='processing')return'Processando';if(s==='failed')return'Falhou';if(s==='uploaded')return'Enviado';return'Arquivado'}
async function readResponse(response:Response){const text=await response.text();if(!text)return{} as any;try{return JSON.parse(text)}catch{return{error:response.status===413?'O arquivo é grande demais para passar pela API. Use o upload direto da Biblioteca.':text.slice(0,300)}}}
function uploadDirectly(signedUrl:string,file:File){const form=new FormData();form.append('cacheControl','3600');form.append('',file);return fetch(signedUrl,{method:'PUT',headers:{'x-upsert':'false'},body:form})}

export function AutocarKnowledgeLibrary({slug,canManage}:{slug:string;canManage:boolean;isMaster?:boolean}){
 const supabase=useMemo(()=>createClient(),[]);const[documents,setDocuments]=useState<KnowledgeDocument[]>([]);const[schemaReady,setSchemaReady]=useState<boolean|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[title,setTitle]=useState('');const[file,setFile]=useState<File|null>(null);
 const token=useCallback(async()=>{const{data}=await supabase.auth.getSession();return data.session?.access_token||''},[supabase]);
 const load=useCallback(async()=>{setBusy(true);try{const access=await token();if(!access)throw new Error('Sessão expirada.');const response=await fetch(`/api/store/portal/autocar/knowledge?slug=${encodeURIComponent(slug)}`,{headers:{Authorization:`Bearer ${access}`},cache:'no-store'});const body=await readResponse(response);if(!response.ok)throw new Error(body.error||'Não foi possível carregar a biblioteca.');setDocuments(body.documents||[]);setSchemaReady(Boolean(body.schema_ready));setMessage(body.schema_ready?'':(body.message||'A Biblioteca ainda aguarda ativação do banco.'))}catch(error:any){setMessage(error?.message||'Não foi possível carregar a Biblioteca AUTOCAR.')}finally{setBusy(false)}},[slug,token]);
 useEffect(()=>{void load()},[load]);
 async function uploadDocument(event:React.FormEvent){event.preventDefault();if(!file||!schemaReady||!canManage)return;if(file.size>MAX_FILE_BYTES){setMessage('O arquivo deve ter no máximo 25 MB.');return}setBusy(true);try{const access=await token();if(!access)throw new Error('Sessão expirada.');setMessage('Preparando upload privado desta loja...');const prep=await fetch('/api/store/portal/autocar/knowledge',{method:'POST',headers:{Authorization:`Bearer ${access}`,'Content-Type':'application/json'},body:JSON.stringify({action:'prepare-upload',slug,scope:'store',title:title||file.name,file_name:file.name,mime_type:file.type,file_size_bytes:file.size})});const pb=await readResponse(prep);if(!prep.ok)throw new Error(pb.error||'Não foi possível preparar o upload.');const upload=pb.upload as PreparedUpload;setMessage(`Enviando ${formatBytes(file.size)} diretamente ao Storage privado...`);const storage=await uploadDirectly(upload.signed_url,file);if(!storage.ok){const b=await readResponse(storage);throw new Error(b.error||`Storage recusou o arquivo (HTTP ${storage.status}).`)}setMessage('Arquivo recebido. Extraindo texto e criando o índice semântico...');const final=await fetch('/api/store/portal/autocar/knowledge',{method:'POST',headers:{Authorization:`Bearer ${access}`,'Content-Type':'application/json'},body:JSON.stringify({action:'finalize-upload',slug,scope:'store',title:title||file.name,file_name:file.name,mime_type:file.type,file_size_bytes:file.size,storage_path:upload.storage_path})});const fb=await readResponse(final);if(!final.ok)throw new Error(fb.error||'O arquivo foi enviado, mas não foi possível concluir a indexação.');setFile(null);setTitle('');await load();setMessage('Conhecimento da loja processado e pronto para consulta pela AUTOCAR.')}catch(error:any){setMessage(error?.message||'Não foi possível processar o documento.')}finally{setBusy(false)}}
 async function archive(document:KnowledgeDocument){if(!canManage||document.scope!=='store')return;setBusy(true);try{const access=await token();const response=await fetch('/api/store/portal/autocar/knowledge',{method:'DELETE',headers:{Authorization:`Bearer ${access}`,'Content-Type':'application/json'},body:JSON.stringify({slug,document_id:document.id})});const body=await readResponse(response);if(!response.ok)throw new Error(body.error||'Não foi possível arquivar.');await load();setMessage('Documento da loja arquivado.')}catch(error:any){setMessage(error?.message||'Não foi possível arquivar.')}finally{setBusy(false)}}
 const methodDocuments=documents.filter(i=>i.scope==='method');const storeDocuments=documents.filter(i=>i.scope==='store');
 return <section className="mt-6 overflow-hidden rounded-[28px] border border-zinc-200 bg-white shadow-sm"><div className="border-b border-zinc-200 p-5 md:p-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex items-center gap-2 text-red-600"><LibraryBig size={18}/><span className="premium-eyebrow">Biblioteca de Inteligência</span></div><h2 className="mt-2 text-2xl font-black text-zinc-950 md:text-3xl">Inteligência herdada + conhecimento da loja</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-600">O Método Venda Mais e a Biblioteca Global são governados pelo Master. Esta loja apenas herda essa inteligência e acrescenta seus materiais operacionais próprios.</p></div><button type="button" onClick={()=>void load()} disabled={busy} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl border border-zinc-200 px-4 text-xs font-black text-zinc-700 disabled:opacity-50"><RefreshCw size={15} className={busy?'animate-spin':''}/>Atualizar</button></div></div>
 <div className="grid gap-5 p-4 md:p-6 xl:grid-cols-[0.78fr_1.22fr]"><form onSubmit={uploadDocument} className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 md:p-5"><div className="flex items-center gap-2"><Store size={18} className="text-red-600"/><h3 className="text-base font-black text-zinc-950">Conhecimento específico desta loja</h3></div><p className="mt-2 text-xs leading-5 text-zinc-600">PDF, DOCX, TXT, Markdown ou CSV. Máximo de 25 MB. Este conteúdo nunca é compartilhado com outra loja.</p><div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-bold text-emerald-800"><BookOpen size={14} className="mr-1 inline"/>Método Venda Mais oficial: herdado do Master e protegido contra edição aqui.</div><label className="mt-4 block text-xs font-black text-zinc-700">Título<input className="premium-input mt-1.5" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: Política de garantia da loja"/></label><label className="mt-3 block text-xs font-black text-zinc-700">Arquivo<input className="premium-input mt-1.5" type="file" accept=".pdf,.docx,.txt,.md,.csv,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain,text/markdown,text/csv" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{file?<div className="mt-2 rounded-xl bg-white px-3 py-2 text-[11px] font-bold text-zinc-600">{file.name} · {formatBytes(file.size)}</div>:null}{!schemaReady?<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3"><LockKeyhole size={15} className="mr-1 inline text-amber-800"/><strong className="text-xs text-amber-800">Banco ainda não ativado</strong></div>:null}<button type="submit" disabled={!canManage||!schemaReady||!file||Boolean(file&&file.size>MAX_FILE_BYTES)||busy} className="mt-4 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-red-600 px-4 text-xs font-black text-white disabled:bg-zinc-300">{busy?<Loader2 size={16} className="animate-spin"/>:<Upload size={16}/>} {busy?'Processando...':'Enviar e indexar'}</button></form><div className="space-y-4"><LibraryGroup title="Método Venda Mais + Biblioteca Global" helper="Herdado do Master · somente leitura nesta loja." icon={<BookOpen size={17}/>} documents={methodDocuments} canArchive={false} onArchive={archive}/><LibraryGroup title="Conhecimento desta loja" helper="Políticas, treinamentos e materiais exclusivos desta operação." icon={<Store size={17}/>} documents={storeDocuments} canArchive={canManage} onArchive={archive}/></div></div>
 <div className="border-t border-zinc-200 bg-zinc-50 px-5 py-4 text-xs leading-5 text-zinc-600"><strong className="text-zinc-900">Contexto AUTOCAR:</strong> Método oficial do Master → Biblioteca Global → conhecimento desta loja → CRM/estoque/lead → conversa.</div>{message?<div className="border-t border-zinc-200 px-5 py-3 text-xs font-bold text-zinc-700">{message}</div>:null}</section>
}
function LibraryGroup({title,helper,icon,documents,canArchive,onArchive}:{title:string;helper:string;icon:React.ReactNode;documents:KnowledgeDocument[];canArchive:boolean;onArchive:(d:KnowledgeDocument)=>void}){return <div className="rounded-2xl border border-zinc-200 p-4 md:p-5"><div className="flex items-center gap-2 text-red-600">{icon}<div><h3 className="text-sm font-black text-zinc-950">{title}</h3><p className="mt-0.5 text-[10px] font-bold text-zinc-400">{helper}</p></div></div><div className="mt-4 space-y-2">{!documents.length?<div className="rounded-xl border border-dashed border-zinc-300 p-4 text-center text-xs font-bold text-zinc-400">Nenhum documento disponível neste ambiente.</div>:documents.map(document=><div key={document.id} className="rounded-xl border border-zinc-200 bg-zinc-50 p-3"><div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-white text-red-600"><FileText size={17}/></div><div className="min-w-0 flex-1"><p className="truncate text-xs font-black text-zinc-900">{document.title}</p><p className="mt-1 truncate text-[10px] font-bold text-zinc-400">{document.original_filename} · {formatBytes(Number(document.file_size_bytes||0))}</p><div className="mt-2 flex flex-wrap gap-2"><span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[9px] font-black uppercase ${document.status==='ready'?'bg-emerald-50 text-emerald-700':document.status==='failed'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{document.status==='ready'?<CheckCircle2 size={11}/>:document.status==='failed'?<XCircle size={11}/>:<Loader2 size={11}/>} {statusLabel(document.status)}</span>{document.chunk_count?<span className="rounded-full bg-white px-2 py-1 text-[9px] font-black text-zinc-500">{document.chunk_count} trechos</span>:null}</div>{document.extraction_error?<p className="mt-2 text-[10px] font-bold text-red-600">{document.extraction_error}</p>:null}</div>{canArchive?<button type="button" onClick={()=>onArchive(document)} className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-zinc-200 bg-white text-zinc-500 hover:text-red-600" title="Arquivar"><Archive size={14}/></button>:null}</div></div>)}</div></div>}
