'use client';

import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Archive, Loader2, Plus, Route, Save } from 'lucide-react';
import { createClient } from '@/lib/supabase';

type Props={scope:'master'|'store'};
const roles=[['pre_sales','Pré-vendas'],['seller','Vendedor'],['prospector','Prospectador']] as const;
const empty={id:'',name:'',status:'active',priority:100,match_type:'default',event_id:'',campaign_key:'',source_key:'',strategy:'round_robin',target_roles:[] as string[],target_member_ids:[] as string[],excluded_member_ids:[] as string[],fixed_user_id:'',starts_at:'',ends_at:''};

export function LeadRoutingRulesManager({scope}:Props){
  const supabase=useMemo(()=>createClient(),[]);
  const [ctx,setCtx]=useState<any>({stores:[],rules:[],members:[],events:[],queue:[]});
  const [storeId,setStoreId]=useState('');
  const [rule,setRule]=useState<any>(empty);
  const [busy,setBusy]=useState(false);
  const [message,setMessage]=useState('');
  async function auth(){const {data}=await supabase.auth.getSession();return data.session?.access_token||'';}
  async function load(id=storeId){setBusy(true);try{const t=await auth();const r=await fetch(`/api/lead-routing-rules${id?`?store_id=${id}`:''}`,{headers:{Authorization:`Bearer ${t}`}});const d=await r.json();setCtx(d);if(!r.ok){setMessage(d.error||'Erro ao carregar.');return;}if(scope==='master'&&!id&&d.stores?.[0]){setStoreId(d.stores[0].id);void load(d.stores[0].id);}if(scope==='store'&&d.store_id)setStoreId(d.store_id);}finally{setBusy(false);}}
  useEffect(()=>{void load('');},[]); // eslint-disable-line react-hooks/exhaustive-deps
  function toggle(field:string,id:string){const a=rule[field]||[];setRule({...rule,[field]:a.includes(id)?a.filter((x:string)=>x!==id):[...a,id]});}
  async function save(){setBusy(true);setMessage('');try{const t=await auth();const r=await fetch(`/api/lead-routing-rules?store_id=${storeId}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify(rule)});const d=await r.json();if(!r.ok)throw new Error(d.error);setRule(empty);setMessage('Regra salva.');await load(storeId);}catch(e:any){setMessage(e?.message||'Erro ao salvar.');}finally{setBusy(false);}}
  async function archive(id:string){setBusy(true);try{const t=await auth();const r=await fetch(`/api/lead-routing-rules?store_id=${storeId}&id=${id}`,{method:'DELETE',headers:{Authorization:`Bearer ${t}`}});const d=await r.json();if(!r.ok)throw new Error(d.error);await load(storeId);}catch(e:any){setMessage(e?.message||'Erro ao arquivar.');}finally{setBusy(false);}}
  function edit(r:any){setRule({...empty,...r,event_id:r.event_id||'',campaign_key:r.campaign_key||'',source_key:r.source_key||'',fixed_user_id:r.fixed_user_id||'',starts_at:r.starts_at?String(r.starts_at).slice(0,16):'',ends_at:r.ends_at?String(r.ends_at).slice(0,16):''});}
  return <div className="p-4 md:p-6"><div className="mx-auto max-w-7xl space-y-4">
    <header className="rounded-3xl bg-slate-950 p-6 text-white"><div className="flex items-center gap-2 text-red-400"><Route size={18}/><span className="text-[10px] font-black uppercase tracking-[.18em]">Roteamento de Leads</span></div><h1 className="mt-2 text-2xl font-black">Motor de distribuição por regra</h1><p className="mt-2 text-sm text-slate-300">Evento → campanha → origem → padrão, com rodízio isolado, fixo, exclusões e fila segura.</p></header>
    {scope==='master'&&<select value={storeId} onChange={e=>{setStoreId(e.target.value);void load(e.target.value);}} className="h-11 w-full rounded-xl border bg-white px-3 text-sm font-bold"><option value="">Selecione a loja</option>{ctx.stores?.map((s:any)=><option key={s.id} value={s.id}>{s.store_name}</option>)}</select>}
    {message&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900"><div className="flex gap-2"><AlertTriangle size={18}/>{message}</div>{ctx.migration_required&&<p className="mt-2 text-xs font-medium">Preview validável sem persistência até a migration ser aplicada em DEV autorizado.</p>}</div>}
    {storeId&&<div className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]">
      <section className="rounded-3xl border bg-white p-5"><div className="flex justify-between"><h2 className="text-xl font-black">{rule.id?'Editar regra':'Nova regra'}</h2><button onClick={()=>setRule(empty)} className="rounded-xl bg-zinc-100 p-2"><Plus size={16}/></button></div>
        <div className="mt-4 grid gap-3 md:grid-cols-2">
          <input className="h-11 rounded-xl border px-3 md:col-span-2" placeholder="Nome da regra" value={rule.name} onChange={e=>setRule({...rule,name:e.target.value})}/>
          <select className="h-11 rounded-xl border px-3" value={rule.match_type} onChange={e=>setRule({...rule,match_type:e.target.value})}><option value="event">Evento</option><option value="campaign">Campanha/Formulário</option><option value="source">Origem</option><option value="default">Padrão</option></select>
          <input className="h-11 rounded-xl border px-3" type="number" value={rule.priority} onChange={e=>setRule({...rule,priority:Number(e.target.value)})}/>
          {rule.match_type==='event'&&<select className="h-11 rounded-xl border px-3 md:col-span-2" value={rule.event_id} onChange={e=>setRule({...rule,event_id:e.target.value})}><option value="">Selecione o evento</option>{ctx.events?.map((e:any)=><option key={e.id} value={e.id}>{e.event_name}</option>)}</select>}
          {rule.match_type==='campaign'&&<input className="h-11 rounded-xl border px-3 md:col-span-2" placeholder="Campanha / formulário" value={rule.campaign_key} onChange={e=>setRule({...rule,campaign_key:e.target.value})}/>} 
          {rule.match_type==='source'&&<input className="h-11 rounded-xl border px-3 md:col-span-2" placeholder="Origem" value={rule.source_key} onChange={e=>setRule({...rule,source_key:e.target.value})}/>} 
          <select className="h-11 rounded-xl border px-3" value={rule.strategy} onChange={e=>setRule({...rule,strategy:e.target.value})}><option value="round_robin">Rodízio uniforme</option><option value="fixed">Responsável fixo</option></select>
          <select className="h-11 rounded-xl border px-3" value={rule.status} onChange={e=>setRule({...rule,status:e.target.value})}><option value="active">Ativa</option><option value="paused">Pausada</option><option value="archived">Arquivada</option></select>
        </div>
        {rule.strategy==='round_robin'?<><p className="mt-4 text-[10px] font-black uppercase text-zinc-500">Cargos</p><div className="mt-2 flex flex-wrap gap-2">{roles.map(([id,label])=><button type="button" key={id} onClick={()=>toggle('target_roles',id)} className={`rounded-full border px-3 py-2 text-xs font-bold ${rule.target_roles.includes(id)?'border-red-300 bg-red-50 text-red-700':''}`}>{label}</button>)}</div><p className="mt-4 text-[10px] font-black uppercase text-zinc-500">Membros</p><div className="mt-2 grid max-h-52 gap-2 overflow-y-auto sm:grid-cols-2">{ctx.members?.map((m:any)=><button type="button" key={m.id} onClick={()=>toggle('target_member_ids',m.id)} className={`rounded-xl border p-3 text-left text-xs ${rule.target_member_ids.includes(m.id)?'border-blue-300 bg-blue-50':''}`}><strong>{m.full_name}</strong><span className="block text-zinc-500">{m.role}{m.receives_leads?'':' · pausado'}</span></button>)}</div></>:<select className="mt-4 h-11 w-full rounded-xl border px-3" value={rule.fixed_user_id} onChange={e=>setRule({...rule,fixed_user_id:e.target.value})}><option value="">Responsável fixo</option>{ctx.members?.map((m:any)=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select>}
        <p className="mt-4 text-[10px] font-black uppercase text-zinc-500">Excluir do recebimento nesta regra</p><div className="mt-2 flex flex-wrap gap-2">{ctx.members?.map((m:any)=><button type="button" key={m.id} onClick={()=>toggle('excluded_member_ids',m.id)} className={`rounded-full border px-3 py-1.5 text-[10px] font-bold ${rule.excluded_member_ids.includes(m.id)?'border-red-300 bg-red-50 text-red-700':''}`}>{m.full_name}</button>)}</div>
        <div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-[10px] font-black uppercase text-zinc-500">Início opcional<input className="mt-1 h-11 w-full rounded-xl border px-3 normal-case" type="datetime-local" value={rule.starts_at} onChange={e=>setRule({...rule,starts_at:e.target.value})}/></label><label className="text-[10px] font-black uppercase text-zinc-500">Fim opcional<input className="mt-1 h-11 w-full rounded-xl border px-3 normal-case" type="datetime-local" value={rule.ends_at} onChange={e=>setRule({...rule,ends_at:e.target.value})}/></label></div>
        <button disabled={busy||!rule.name||ctx.migration_required} onClick={()=>void save()} className="mt-4 inline-flex h-11 items-center gap-2 rounded-xl bg-red-600 px-5 text-xs font-black uppercase text-white disabled:opacity-40">{busy?<Loader2 className="animate-spin" size={16}/>:<Save size={16}/>}Salvar regra</button>
      </section>
      <aside className="space-y-4"><section className="rounded-3xl border bg-white p-5"><h3 className="font-black">Regras da loja</h3><div className="mt-3 space-y-2">{ctx.rules?.filter((r:any)=>r.status!=='archived').map((r:any)=><div key={r.id} className="flex items-center justify-between rounded-xl border p-3"><button className="text-left" onClick={()=>edit(r)}><strong className="block text-sm">{r.name}</strong><span className="text-[10px] uppercase text-zinc-400">{r.match_type} · {r.strategy} · {r.priority}</span></button><button onClick={()=>void archive(r.id)} className="p-2 text-zinc-400"><Archive size={15}/></button></div>)}</div></section><section className="rounded-3xl border border-amber-200 bg-amber-50 p-5"><h3 className="font-black text-amber-950">Fila não distribuída</h3><p className="mt-1 text-xs text-amber-800">Regra encontrada sem destinatário elegível não cai em fallback silencioso.</p><div className="mt-3 text-3xl font-black">{ctx.queue?.length||0}</div></section></aside>
    </div>}
  </div></div>;
}
